version: '3'

services:
  node: 
    build: 
      context: ./node
    image: nathanreys/node:fullcycle
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh
    command: node index.js
    networks: 
      - node-network
    # Volume desabilitado pois não se busca persistência de dados neste momento
    #volumes: 
    #  - ./node:/usr/src/app
    tty: true
    #ports: # Sem exposição de porta do node
    #  - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    # Volume desabilitado pois não se busca persistência de dados neste momento
    #volumes:
    #  - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  nginx: 
    build: 
      context: ./nginx
    image: nathanreys/nginx:fullcycle
    container_name: nginx
    networks: 
      - node-network
    ports:
      - "8080:80"

networks:
  node-network:
    driver: bridge